version: '3.8'

services:
  hugo:
    build: .
    ports:
      - "1313:1313"
    volumes:
      - .:/src
    working_dir: /src
    command: hugo server --bind 0.0.0.0 --buildDrafts --buildFuture --watch
    environment:
      - HUGO_BASEURL=http://localhost:1313

  hugo-new:
    build: .
    volumes:
      - .:/src
    working_dir: /src
    profiles:
      - setup
    command: hugo new site . --force